### ISSUE TITLE
General suggestions for the Spices website

### ISSUE THREAD

**Issue by Odyseus** [clefebvre/cinnamon-spices#10] opened 2017-02-13 14:49 UTC
### General improvements

- [ ] Create an **About** or **Disclaimer** page where it is specified in details what the Spices website is, how does it work and who are the actual providers of the published xlets/spices. A good example would be the [Mozilla About page](https://addons.mozilla.org/en-GB/about) on their AMO (addons.mozilla.org) website. It just makes sense.
- [ ] Do not just remove obsolete/abandoned/broken xlets. Practical reasons. Move them to another "archive" repository for historical purposes and in case an author comes back and decides to update it. The documentation for creating any type of xlet is absolutely basic, to say the least. And the only way to know how *things are done* is by looking at other xlets. While an xlet removed from the *cinnamon-spices-[xlets]* repositories is still in their GitHub history, it would be absolutely tedious to search for each and every one of them.

### Applets/desklets/extensions/themes pages improvements

- [ ] Use the xlet name as page title for each xlet page. Practical reasons. I'm referring to the **title** inside the **head** tag on a web page and whose text will then be displayed on the browser's tab.
- [ ] The name of the author should be a link to the author's GitHub page. Practical reasons and to satisfy "sense of ownership".
- [ ] The **Home** link on the page header (top bar) could be removed and its link could be added to the site's logo. Aesthetic and practical reasons. It will also avoid the "deformation" of the header content on low resolutions.

- [ ] The **Website** button next the the **Download** button should point to a website defined by the xlet author. Practical reasons. I particularly will request that all issues related to my xlets and opened (for whatever reason) on the *cinnamon-spices-[xlets]* repositories to be closed and re-opened in my repository. For the simple reason that I already have in place my own system and work-flow with my own tags and issue templates. This will also help to reduce the amount of issues that a repository reviewer has to manage and *moderate*.
    - The already defined website on the **metadata.json** files could be the source of it.
    - Or a new property could be added to the **info.json** file called *website* and define the custom website in there.
- [ ] All entries in the pages *header* should be highlighted in bold. Aesthetic and practical reasons.
- [ ] The **Last edited** entry should be renamed to **Last updated**. The latter is contextually more meaningful. Practical reasons.
- [ ] The **Last commit** entry should be renamed to **Changelog** or **History**, since the link points to the commits history for the xlet. Practical reasons. As mentioned in #2 by @Piiit, the commit hash is kind of useless (I'm paraphrasing). At the moment, it doesn't occur to me for what the commit hash could be replaced with. Maybe simply **GitHub history**?

#### Implemented

- [x] Use the xlet logo at the beginning of the xlet name. Not applicable to themes. Not just for aesthetic reasons. It also helps to better recognize an xlet by its logo.
- [x] Use the new Spices logo as favicon. Aesthetic reasons.
- [x] Images aren't scaled with their containers. Aesthetic reasons. Big images exceed the boundaries of the pages containers. A simple CSS fix could be:

```css
img {
    max-width: 100%;
}
```

#### Implemented
- [x] Do not use the **screenshot.png** file as a thumbnail for each theme. Practical reasons. This page loading time is absolutely ridiculous.
    1. There could be a file called **thumbnail.png** at the same level as the **screenshot.png** file and use that instead. The **thumbnail.png** file would be a reduced image (of about 390x220 pixels, for example) based on the **screenshot.png** file.
    2. Or the thumbnail could be automatically generated on the server side based on the **screenshot.png**. But I don't know how demanding this could be. It costs us (theme authors) nothing doing what I describe in point **1** and it probably needs to done just once on the theme's life time.

**Comment by NikoKrause** [comment] 2017-02-13 17:01
> Do not just remove obsolete/abandoned/broken xlets. Practical reasons. Move them to another "archive" repository for historical purposes and in case an author comes back and decides to update it. The documentation for creating any type of xlet is absolutely basic, to say the least. And the only way to know how things are done is by looking at other xlets. While an xlet removed from the cinnamon-spices-[xlets] repositories is still in their GitHub history, it would be absolutely tedious to search for each and every one of them.

The applets, which were removed till now were abandoned broken applets or obsolete applets. The broken ones were only deleted, when they had a working fork, e.g. some applets only exists because the author abandoned his applet and ignored fixes in the comments of his applet. People forked those and fixed them. There's no need in keeping both applets, the broken and the fixed, if they don't have significant other differences. 
Some bigger applets as StarkMenu were deleted because it's unlikely that somebody will fix it in the near future, because it's a big project. Now that there's a replacement for it, it has been deleted.
The classicMenu on the other hand is also a big broken project, which hasn't been deleted, because it has no working replacement. But it's also unlikely to be fixed in the near future, if nobody comes along who wants to do this. The Menu applets are big and have one bug after the other. Especially, when they are pretty old. (You know it on your own, because you develope one by yourself.)
The obsolete applets have been deleted, because they were broken and their functionality is implemented with Cinnamon itself now. There would be no purpose in developing this applet, when the author doesn't.

An archive for deleted applets was proposed as well. (I don't know if it would be great in having an easy accessible repo with lots of broken code in it.)
Deleted Applets are not very hard to find in the repo. They are marked with the label `APPELT REMOVAL`

>  The name of the author should be a link to the author's GitHub page. Practical reasons and to satisfy "sense of ownership".

I thought about this as well and wanted to propose this too.
A lot of authors yet are still wrong in the info.json files. Some can be fixed. I'll do this for a few applets very soon. But some authors don't have a GitHub repo or if they have one, it's not obvious to find them.

> The Website button next the the Download button should point to a website defined by the xlet author. Practical reasons. I particularly will request that all issues related to my xlets and opened (for whatever reason) on the cinnamon-spices-[xlets] repositories to be closed and re-opened in my repository. For the simple reason that I already have in place my own system and work-flow with my own tags and issue templates.

This won't be practical. The devs should be encouraged to work with the cinnamon-spices-repo.
The website button links to the place, where the code is stored, which you can download from the spices website. 
It would be a mess, if this would be split up, where you have 50-60 developers, where each one of them has his own repository and wants the issue on the spices repo to be closed and opened in the repo of the author. The reviewers will need to remember of each one them, which issue to close and direct the users to the right place and which not. You would be a mess. 
I know it's hard to break the work-flow, if you are used to it. But in the long rong it would be easier to switch to the spices repo. (That's only my opinion, though.)

> The Last commit entry should be renamed to Changelog or History,
Yes this could be done. But sometimes it's still usefull to know, which commit is shown as last in the spices repo.

**Comment by Odyseus** [comment] 2017-02-15 01:20
Hello, @NikoKrause.

#### About xlets deletion

Now that I think of it, this repository wasn't the right place to suggest this (kind of off-topic here).

The part were I said *"in case an author comes back"* isn't really important. The *"historical purposes"* is what I consider important. My thinking is as follows. All code, broken or not, is important. Not just to see *how things are done*, but to see *how things were done and/or shouldn't be done anymore*.

I suggested an *"archive"* repository because a GitHub repository is the simplest way of sharing files, keep them updated and download them in bulk.

> I don't know if it would be great in having an easy accessible repo with lots of broken code in it.

If your worry is the certain probability that the broken code will cause damage, then you don't have to worry at all. With a simple README that informs what all the code hosted is/was (obsolete xlets) and for what reason does it exists (historical reason), you can move on with a clear conscience. No need for the *hand-holding*. LOL

> Deleted Applets are not very hard to find in the repo.

The problem isn't how to find them. The *problem* is that, once the deleted xlets are found, one is forced to download **the entire repository** in that point on history just to get a couple of xlets that were removed. Or to download each file individually from the pull requests that removed each applet. I can't decide which method would be more of a mortal wound to my patience! LOL

#### About the link to the author's GitHub page

In the mean time, active developers could have the option to set a property on the **info.json** file called, for example, **has-github-account**. The Spices website could automatically create the link to the author's GitHub page for the Spices pages that have that property set to true and ignore the ones that doesn't. Just a thought. Because if you will wait for every single xlet author to be correctly specified on the **info.json** files, then this improvement may never happen. Because some xlets might stay abandoned forever and/or some developers may choose to never create a GitHub account.

#### About the Website button

> The devs should be encouraged to work with the cinnamon-spices-repo.

The *cinnamon-spices-[xlets]* repositories are just a *hosting place* for me and will continue to be so. For the simple fact that none of my xlets in my repository are in sync with the ones published on the Spices website and never will be. I upload beta version into my repository and I only upload to the Spices repositories when I consider that my xlets are stable enough.

> The website button links to the place, where the code is stored, which you can download from the spices website.

The **Website** button links to a completely irrelevant place for an end user. An end user wouldn't know what to do with the code provided because the first files shown are those used internally by the Spices website (info.json, screenshot.png, etc.) and/or files put in there because are irrelevant for the xlet to function. And the information shown by its README is the exact same information shown on the Spices website.

> It would be a mess...

The whole point of linking the **Website** button to a location defined by the author is precisely to avoid the *mess* you are talking about. Because all the issues will be handled directly by the one that will **actually fix the issue** (the xlet author). The repository reviewers are just being witnesses in a conversation between author and issue reporter and just waiting there for the issue to be resolved to be able to close it. That sounds to me more like a moderator in a forum than a reviewer.

In my opinion, the *cinnamon-spices-[xlets]* repositories' reviewers should only be dealing with the xlets authors and contributors **and no one else**. And **only** deal with issue reports from abandoned xlets.

> I know it's hard to break the work-flow...

There is no work-flow to speak of. The xlet author has no control whatsoever over anything that happens in any of the *cinnamon-spices-[xlets]* repositories nor should he ever have it (Trusted or not, reviewer or not, all code should be reviewed).

#### About the Last commit entry

> But sometimes it's still usefull to know, which commit is shown as last in the spices repo.

From an end user's point of view, the commit hashes are never useful. From an xlet author's or contributor's point of view, we already know were to look at the last commit hash.

**Comment by NikoKrause** [comment] 2017-04-03 16:24
> The name of the author should be a link to the author's GitHub page. Practical reasons and to satisfy "sense of ownership"

I think that's a good idea.
Since a lot of authors are still unknown this maybe could be done with a flag in the info.json file?
Wie could add the flag
```
verified: true
```
or something like that in the info.json file.
The spices site could check, if this flag exists. If it does, it could create a link as suggested.
E.g. Force Quit by [clefebvre](www.github.com/clefebvre)

**Comment by pdcurtis** [comment] 2017-04-30 11:27
The latest version of the Spices Website is a big step forwards. The login seems to be very fast and seamless if you have a gmail account. 
It seems a little petty to put forward extra suggestions so early on but:
 * It is difficult to search for a spice or type of spice. There is no search box yet and the pagination means that one can not do a search of all the spices using the browser search. This tends at present to give priority to applets with a title at the start of the alphabet.
 * I am not sure about removing all the previous comments, it does mean that many of the warnings have been lost and it is more difficult to understand whether there is an active author as the updates are primarily translations and are not an indicator that the author is active or that the applet works with the latest versions of Cinnamon.

The web site does not display well on my tablet (in mobile firefox) which has a screen resolution higher than many laptops - rotation did not fully solve the problem and 'display the original web site' made no difference either. Some of the text in 'boxes' is truncated and some disappear at top left. It is however OK on the 1024 x 600 screen on my old Netbook which I hauled out to check, so I am not sure what the problem can be.

**Comment by MrElectroNick** [comment] 2017-05-12 13:02
@Odyseus Themes page is improved now - previews are now used instead of theme screenshot.png - page loads much faster now. So you can mark this item as done

**Comment by Odyseus** [comment] 2017-05-12 16:18
Infinite thanks, @MrElectroNick!

I just tested it and it loads immediately. Keep up the great job. 👍

**Comment by NikoKrause** [comment] 2017-08-17 16:33
Regarding the request:
> The name of the author should be a link to the author's GitHub page. Practical reasons and to satisfy "sense of ownership".

The authors of applets, desklets and extensions now are currently active and confirmed GitHub usernames. (as checked here https://github.com/linuxmint/cinnamon-spices-applets/issues/668)

Right now I'm checking the authors of themes and waiting for confirmation: https://github.com/linuxmint/cinnamon-spices-themes/issues/221

As soon as this is done, nothing should speak against this feature.

**Comment by nyrrad** [comment] 2017-08-18 01:59
Once the theme authors are confirmed let me know and ill implement it :+1:

**Closed** 2017-08-18 14:34 UTC

**Comment by NikoKrause** [comment] 2017-09-06 15:23
@nyrrad 
When this https://github.com/linuxmint/cinnamon-spices-themes/pull/241 and this https://github.com/linuxmint/cinnamon-spices-themes/pull/222 gets merged, then there are only 4 authors left to check.

One author has a Google+ account. I don't have G+. Can you ask him for his GitHub username?
It's this one https://plus.google.com/communities/105043009531408262017

**Comment by nyrrad** [comment] 2017-09-10 03:43
@NikoKrause I sent him a message on hangouts, we'll see if he responds. I'll let you know
